# Generated by Django 5.2.4 on 2025-07-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExchangePropsal',
            new_name='ExchangeProposal',
        ),
    ]
