# Generated by Django 5.2.4 on 2025-07-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_rename_exchangepropsal_exchangeproposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('электроника', 'Электроника'), ('одежда', 'Одежда'), ('мебель', 'Мебель'), ('книги', 'Книги'), ('другое', 'Другое')], default='другое', max_length=50),
        ),
        migrations.AlterField(
            model_name='ad',
            name='condition',
            field=models.CharField(choices=[('новое', 'Новое'), ('б/у', 'Б/у')], default='б/у', max_length=20),
        ),
    ]
